[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=41
    -DTFT_SCLK=40
    -DTFT_CS=39
    -DTFT_DC=38
    -DTFT_RST=42
    -DLOAD_GLCD=1
    -O3

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43

board_build.embed_txtfiles = 
    ps.bin
